name: AWS CLI Action Example

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch

jobs:
  aws:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repo

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify your region here

    - name: List S3 Buckets
      run: aws s3 ls  # List all S3 buckets in your AWS account
